CFLAGS = -pthread - Wall -02

simulator: simulator.c
	gcc -o simulator simulator.c utility.c -Wall

overseer: overseer.c
	gcc -o overseer overseer.c utility.c -Wall

cardreader: cardreader.c
	gcc -o cardreader cardreader.c utility.c -Wall

door: door.c
	gcc -o door door.c utility.c -Wall

firealarm: firealarm.c
	gcc -o firealarm firealarm.c utility.c -Wall

callpoint: callpoint.c
	gcc -o callpoint callpoint.c utility.c -Wall

destselect: destselect.c
	gcc -o destselect destselect.c utility.c -Wall

elevator: elevator.c
	gcc -o elevator elevator.c utility.c -Wall

camera: camera.c
	gcc -o camera camera.c utility.c -Wall